# Basic metadata configuration for your blog.
theme = "rtc"
title = "St. Brendan-Projekt"
author = "DSL"
copyright = ""
languageCode = "de-CH"

# Generate robots.txt for SEO
enableRobotsTXT = false

# Set to "WARNING" so that broken links don't break the build process. Default is "ERROR".
refLinksErrorLevel = "WARNING"
