name: Create editioncrafter assets, and build and deploy hugo site

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    env:
      HUGO_VERSION: 0.137.1

    steps:

    # repo checkout
      - name: Checkout
        uses: actions/checkout@v4

    # install hugo
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass

    # setup editioncrafter
      - name: Install EditionCrafter
        run: npm install -g @cu-mkp/editioncrafter-cli

    # build minified hugo site
      - name: Hugo Build
        run: |
          mkdir -p public/edition && \
          editioncrafter process -i ./st-brendan.xml -o ./public/edition -u /st-brendan/edition && \
          hugo --minify

    # deploy

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: 'St-Brendan-edition'
          path: 'public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          name: 'St-Brendan-edition'
